Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Excluded:
  - src/zipstream/http/server/handlers/static_file_handler.cr
  Enabled: true
  Severity: Warning

Lint/ShadowingOuterLocalVar:
  Description: Disallows the usage of the same name as outer local variables for block
    or proc arguments
  Excluded:
  - src/zipstream/http/server/handlers/static_file_handler.cr
  Enabled: true
  Severity: Warning

Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - src/zipstream/http/server/handlers/static_file_handler.cr
  Enabled: true
  Severity: Warning

Documentation/DocumentationAdmonition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
