name: zipstream
base: core24
version: '0.25.3'
title: Zipstream
summary: Easily share files and directories over the network
description: |
  A command-line tool that allows you to easily share files and directories
  over the network.

  **Snap-specific information**

  Due to the snap's confined nature, the application can only access files in the user's home directory.
  To access files under `/media` or `/mnt` directories you have to manually connect the snap
  to the `removable-media` interface by running the following command in a terminal

  `sudo snap connect zipstream:removable-media`
icon: snap/gui/logo.png
contact: anton.maminov@gmail.com
type: app

grade: stable
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
compression: lzo

license: MIT

website: https://github.com/mamantoha/zipstream
issues: https://github.com/mamantoha/zipstream/issues
source-code: https://github.com/mamantoha/zipstream.git

apps:
  zipstream:
    command: bin/zipstream
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  zipstream:
    source: ./
    plugin: nil
    build-snaps:
      - crystal/latest/stable
    build-packages:
      - git
      - libevent-dev
      - libgc-dev
      - libpcre2-dev
      - libssl-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - libevent-2.1-7
      - libgc1
      - libpcre2-8-0
      - libssl3
      - zlib1g
    override-build: |
      shards install --production
      shards build --release -- -Dpreview_mt -Dexecution_context
      install -Dm755 bin/zipstream "$CRAFT_PART_INSTALL/bin/zipstream"
