name: zipstream
base: core20
version: '0.22.5'
summary: Easily share files and directories over the network
description: |
  A command-line tool that allows you to easily share files and directories
  over the network.

  **Snap-specific information**

  Due to the snap's confined nature, the application can only access files in the user's home directory.
  To access files under `/media` or `/mnt` directories you have to manually connect the snap
  to the `removable-media` interface by running the following command in a terminal

  `sudo snap connect zipstream:removable-media`
icon: snap/gui/logo.png
contact: anton.maminov@gmai.com
type: app

grade: stable
confinement: strict
architectures: [amd64]
compression: lzo

license: MIT

website: https://github.com/mamantoha/zipstream
issues: https://github.com/mamantoha/zipstream/issues
source-code: https://github.com/mamantoha/zipstream.git

apps:
  zipstream:
    command: bin/zipstream
    plugs:
      - network
      - network-bind
      - home
      - removable-media

parts:
  zipstream:
    source: ./
    plugin: crystal
    build-packages:
     - git
     - libssl-dev
    crystal-build-options:
    - -Dpreview_mt
